import React from 'react'
import $ from 'jquery'
require('../../../css/home.css')
import {BaseLi,SubmitOk} from '../../../../../common/assembly/Stateless';
import { Switch } from 'antd'
export default class NewAddress extends React.Component{
    constructor(props){
        super(props);
        this.state={

        }
        this.buquan=()=>{
            this.props.history.pushState({comnews:'1'},'/news/personnews')
        }
        this.updata=()=>{
            if(this.state.orgType=='0'){
                console.log("0000")
                this.props.setProps({news:{
                    xlcname:this.state.registerName,
                    orgType:0,
                    xlcaddrDetail:this.state.addrDetail,
                    xlcNames:this.state.orgName,
                    xlcshotname:this.state.orgShotName,
                    sfval:this.state.proviceName,
                    repairLevel:this.state.repairLevel,
                    sfid:this.state.proviceId,
                    sqid:this.state.cityId,
                    sqval:this.state.cityName,
                    qyid:this.state.areaId,
                    qyval:this.state.areaName,
                    isDefault:this.state.isDefault,
                    flag:1,
                    addressId:this.state.addressId
                }})
            }else if(this.state.orgType=='1'){
                console.log("1111")
                this.props.setProps({news:{
                    insurancename:this.state.registerName,
                    orgType:1,
                    insuranceaddrDetail:this.state.addrDetail,
                    insurancecompany:this.state.orgName,
                    sfval:this.state.proviceName,
                    sfid:this.state.proviceId,
                    sqid:this.state.cityId,
                    sqval:this.state.cityName,
                    qyid:this.state.areaId,
                    qyval:this.state.areaName,
                    isDefault:this.state.isDefault,
                    flag:1,
                    addressId:this.state.addressId
                }})
            }else{
                console.log("9999")
                this.props.setProps({news:{
                    name:this.state.registerName,
                    orgType:9,
                    addrDetail:this.state.addrDetail,
                    sfval:this.state.proviceName,
                    sfid:this.state.proviceId,
                    sqid:this.state.cityId,
                    sqval:this.state.cityName,
                    qyid:this.state.areaId,
                    qyval:this.state.areaName,
                    isDefault:this.state.isDefault,
                    flag:1,
                    addressId:this.state.addressId
                }})
            }
            this.props.history.pushState(null,'/updataperson')
        }
    }
    componentWillMount(){
        this.props.ajax({
            url:'/toumingxiu/personalRegister/queryPersonalAdditionalInfo.do',
            data:{userId:this.props.user.data.LxAqYhxxb.id},
            suc:(dat)=>{
                console.log(dat)
                console.log(this.props.user.data.LxAqYhxxb.id)
                console.log(dat.personalAdditionalInfo.addressId)
                this.setState({
                    personalAdditionalInfo:dat.personalAdditionalInfo
                })
                if(dat.personalAdditionalInfo){
                    this.props.ajax({
                        url:'/server/lexiu1-app/api/tmxcorder/listAddrs?token='+this.props.user.data.token,
                        data:{
                            customerId:this.props.user.data.LxAqYhxxb.id,
                            isDefault:'',
                            id:dat.personalAdditionalInfo.addressId
                        },
                        suc:(data)=>{
                            console.log(data)
                            let list=data.list
                            console.log(list)
                            if(list.length>0){
                                console.log("asaaa")
                                this.setState({
                                    orgType:dat.personalAdditionalInfo.orgType,
                                    registerName:dat.personalAdditionalInfo.registerName,
                                    address:dat.personalAdditionalInfo.address,
                                    orgName:dat.personalAdditionalInfo.orgName,
                                    orgShotName:dat.personalAdditionalInfo.orgShotName,
                                    addressId:dat.personalAdditionalInfo.addressId,
                                    proviceName:list[0].addr1,
                                    proviceId:list[0].addr1Id,
                                    repairLevel:list[0].repairLevel,
                                    cityName:list[0].addr2,
                                    cityId:list[0].addr2Id,
                                    areaName:list[0].addr3,
                                    areaId:list[0].addr3Id,
                                    addrDetail:list[0].addrDetail,
                                    isDefault:list[0].isDefault
                                })
                            }else{
                                this.setState({
                                    orgType:dat.personalAdditionalInfo.orgType,
                                    registerName:dat.personalAdditionalInfo.registerName,
                                    address:dat.personalAdditionalInfo.address,
                                    orgName:dat.personalAdditionalInfo.orgName,
                                    orgShotName:dat.personalAdditionalInfo.orgShotName,
                                    addressId:'',
                                    proviceName:'',
                                    proviceId:'',
                                    repairLevel:'',
                                    cityName:'',
                                    cityId:'',
                                    areaName:'',
                                    areaId:'',
                                    addrDetail:'',
                                    isDefault:false
                                })
                            }
                        }
                    })
                }
            }
        })
    }
    componentDidMount(){
        this.props.changeTitle('基本信息')
    }
    render(){
        console.log(this.props)
        console.log(this.state)
        var repairlev=''
        if(this.state.repairLevel=='0') {
            repairlev='4S'
        }else if(this.state.repairLevel=='1'){
            repairlev='一类'
        }else if(this.state.repairLevel=='2'){
            repairlev='二类'
        }else if(this.state.repairLevel=='3'){
            repairlev='三类'
        }else{
            repairlev='综合'
        }
        console.log(repairlev)
        console.log(this.state.repairLevel)
        console.log(this.state.repairLevel=='4')
        return(
            <div className="person1">
                {this.state.orgType=='9'&&<ul>
                    <li>
                        <span>姓名</span>
                        <span>{this.state.registerName}</span>
                    </li>
                    <li>
                        <span>所在地区</span>
                        <span>
                            <p>{this.state.proviceName}</p>
                            <p>{this.state.cityName}</p>
                            <p>{this.state.areaName}</p>
                        </span>
                    </li>
                    <li>
                        <span>详细地址</span>
                        <span>
                            <p>{this.state.addrDetail}</p>
                        </span>
                    </li>
                </ul>}
                {this.state.orgType=='0'&&<ul>
                    <li>
                        <span>姓名</span>
                        <span>{this.state.registerName}</span>
                    </li>
                    <li>
                        <span>修理厂名称</span>
                        <span>{this.state.orgName}</span>
                    </li>
                    <li>
                        <span>修理厂简称</span>
                        <span>{this.state.orgShotName}</span>
                    </li>
                    <li>
                        <span>所在地区</span>
                        <span>
                            <p>{this.state.proviceName}</p>
                            <p>{this.state.cityName}</p>
                            <p>{this.state.areaName}</p>
                        </span>
                    </li>
                    <li>
                        <span>详细地址</span>
                        <span>
                            <p>{this.state.addrDetail}</p>
                        </span>
                    </li>
                    <li>
                        <span>维修资质</span>
                        <span>{repairlev}</span>
                    </li>
                </ul>}
                {this.state.orgType=='1'&&<ul>
                    <li>
                        <span>姓名</span>
                        <span>{this.state.registerName}</span>
                    </li>
                    <li>
                        <span>保险公司名称</span>
                        <span>{this.state.orgName}</span>
                    </li>
                    <li>
                        <span>所在地区</span>
                        <span>
                            <p>{this.state.proviceName}</p>
                            <p>{this.state.cityName}</p>
                             <p>{this.state.areaName}</p>
                        </span>
                    </li>
                    <li>
                        <span>详细地址</span>
                        <span>
                            <p>{this.state.addrDetail}</p>
                        </span>
                    </li>
                </ul>}
                {this.state.personalAdditionalInfo==null?<div style={{width:'100vw',height:'1rem',marginTop:'0.5rem'}}>
                        <button onClick={this.buquan} style={{border:'0px',width:'92%',height:'1rem',marginLeft:'4%',background:'#3A97F7',color:'#fff',borderRadius:'0.1rem',fontSize:'0.32rem'}}>补全信息</button>
                    </div>:<div style={{width:'100vw',height:'1rem',marginTop:'0.5rem'}}>
                    <button onClick={this.updata} style={{border:'0px',width:'92%',height:'1rem',marginLeft:'4%',background:'#3A97F7',color:'#fff',borderRadius:'0.1rem',fontSize:'0.32rem'}}>修改</button>
                </div>}
            </div>
        )
    }
}